# render.yaml

services:
  - type: web
    name: nestjs-app
    env: node
    region: frankfurt  # Выберите ближайший к вам регион, например, frankfurt для Европы
    plan: free
    buildCommand: yarn install
    startCommand: yarn start:prod
    autoDeploy: true


